// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalInmobiliario.Data;

#nullable disable

namespace PortalInmobiliario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250927022424_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PortalInmobiliario.Models.Inmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Banos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inmuebles", t =>
                        {
                            t.HasCheckConstraint("CK_Inmueble_MetrosCuadrados", "MetrosCuadrados > 0");

                            t.HasCheckConstraint("CK_Inmueble_Precio", "Precio > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Banos = 2,
                            Ciudad = "Lima",
                            Codigo = "DEP001",
                            Direccion = "Av. Larco 123",
                            Dormitorios = 2,
                            MetrosCuadrados = 80,
                            Precio = 150000m,
                            Tipo = 0,
                            Titulo = "Depa Miraflores"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Banos = 2,
                            Ciudad = "Arequipa",
                            Codigo = "CAS001",
                            Direccion = "Calle Real 456",
                            Dormitorios = 3,
                            MetrosCuadrados = 120,
                            Precio = 250000m,
                            Tipo = 1,
                            Titulo = "Casa Arequipa"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Banos = 1,
                            Ciudad = "Lima",
                            Codigo = "OFC001",
                            Direccion = "Av. Javier Prado 789",
                            Dormitorios = 0,
                            MetrosCuadrados = 60,
                            Precio = 180000m,
                            Tipo = 2,
                            Titulo = "Oficina San Isidro"
                        });
                });

            modelBuilder.Entity("PortalInmobiliario.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("InmuebleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("PortalInmobiliario.Models.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("InmuebleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId");

                    b.ToTable("Visitas", t =>
                        {
                            t.HasCheckConstraint("CK_Visita_Fechas", "FechaInicio < FechaFin");
                        });
                });

            modelBuilder.Entity("PortalInmobiliario.Models.Reserva", b =>
                {
                    b.HasOne("PortalInmobiliario.Models.Inmueble", "Inmueble")
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("PortalInmobiliario.Models.Visita", b =>
                {
                    b.HasOne("PortalInmobiliario.Models.Inmueble", "Inmueble")
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });
#pragma warning restore 612, 618
        }
    }
}
